name: update contribution chart

on:
  schedule:
    - cron: "0 0 * * *"     # todo dia à meia-noite
  workflow_dispatch:         # permite rodar manualmente
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: pipipi-dev/gcchart@v1
        with:
          outputs: |
            contributions.svg
